def _has_rdkit_and_pandas(m):
    try:
        m._load_heavy()
        return bool(getattr(m, "_CHEM_READY", False)) and getattr(m, "pd", None) is not None
    except Exception:
        return False


def _write_one_row_csv(tmp_path, filename, smiles):
    p = tmp_path / filename
    p.write_text(f"NAME,SMILES\nX,{smiles}\n", encoding="utf-8")
    return str(p)


def test_golden_biginelli_product_smiles(tmp_path):
    import mcrg_desktop as m

    if not _has_rdkit_and_pandas(m):
        return

    alde = _write_one_row_csv(tmp_path, "alde.csv", "O=Cc1ccccc1")
    keto = _write_one_row_csv(tmp_path, "keto.csv", "CC(=O)CC(=O)OC")

    df_all, df_ideal, _ = m.run_mcr(
        "Biginelli (3-CR)",
        [alde, keto],
        core_smiles_list=[("Urea", "[NH2]C(=O)[NH2]")],
        threshold=0.0,
        ideal_rule="Lipinski",
    )

    assert len(df_all) == 1
    assert len(df_ideal) == 1
    # Golden: canonical SMILES of first product (regression guard for SMARTS changes)
    assert df_all.iloc[0]["SMILES_Final"] == "COC(=O)C1=C(C)NC(=O)NC1c1ccccc1"
    assert "InChIKey" in df_all.columns


def test_golden_mannich_no_product_reason(tmp_path):
    import mcrg_desktop as m

    if not _has_rdkit_and_pandas(m):
        return
    if "Mannich (3-CR)" not in m.MCR_CATALOGO:
        return

    alde = _write_one_row_csv(tmp_path, "alde.csv", "O=Cc1ccccc1")
    amine = _write_one_row_csv(tmp_path, "amine.csv", "CN")
    keto = _write_one_row_csv(tmp_path, "keto.csv", "CC(=O)CC(=O)OC")

    df_all, df_ideal, _ = m.run_mcr("Mannich (3-CR)", [alde, amine, keto], threshold=0.0, ideal_rule="Lipinski")
    assert len(df_all) == 1
    assert len(df_ideal) == 0
    assert df_all.iloc[0]["Classification"] == "Discarded"
    assert df_all.iloc[0]["Failure_Reason"] == "No products generated by reaction SMARTS"


def test_golden_petasis_no_product_reason(tmp_path):
    import mcrg_desktop as m

    if not _has_rdkit_and_pandas(m):
        return
    if "Petasis (3-CR)" not in m.MCR_CATALOGO:
        return

    alde = _write_one_row_csv(tmp_path, "alde.csv", "O=Cc1ccccc1")
    amine = _write_one_row_csv(tmp_path, "amine.csv", "CN")
    bor = _write_one_row_csv(tmp_path, "bor.csv", "B(O)(O)C=C")

    df_all, df_ideal, _ = m.run_mcr("Petasis (3-CR)", [alde, amine, bor], threshold=0.0, ideal_rule="Lipinski")
    assert len(df_all) == 1
    assert len(df_ideal) == 0
    assert df_all.iloc[0]["Classification"] == "Discarded"
    assert df_all.iloc[0]["Failure_Reason"] == "No products generated by reaction SMARTS"

