from pathlib import Path


def _has_rdkit_and_pandas(m):
    try:
        m._load_heavy()
        return bool(getattr(m, "_CHEM_READY", False)) and getattr(m, "pd", None) is not None
    except Exception:
        return False


def _write_one_row_csv(tmp_path, filename, smiles):
    p = tmp_path / filename
    p.write_text(f"NAME,SMILES\nX,{smiles}\n", encoding="utf-8")
    return str(p)


def test_official_gbb_and_gewald_example_packs_generate_ideals():
    import mcrg_desktop as m

    if not _has_rdkit_and_pandas(m):
        return

    root = Path(__file__).resolve().parents[1]

    gbb_all, gbb_ideal, _ = m.run_mcr(
        "GBB (3-CR)",
        [
            str(root / "examples" / "aldehydes.csv"),
            str(root / "examples" / "isocyanides.csv"),
            str(root / "examples" / "aminoazines.csv"),
        ],
        threshold=0.0,
        ideal_rule="Lipinski",
    )
    assert len(gbb_all) > 0
    assert len(gbb_ideal) > 0
    assert (gbb_all["Classification"] == "Ideal").any()
    gbb_summary = gbb_all.attrs.get("run_summary", {})
    assert gbb_summary["evaluated"] == 504
    assert gbb_summary["products_valid"] > gbb_summary["ideal_unique"] > 0
    assert gbb_summary["warning"] > 0
    assert gbb_summary["error"] > 0
    assert (gbb_all["Review_Status"] == "Warning").any()
    assert (gbb_all["Review_Status"] == "Error").any()
    assert gbb_all.attrs.get("preflight")

    gewald_all, gewald_ideal, _ = m.run_mcr(
        "Gewald (3-CR)",
        [
            str(root / "examples" / "ketones.csv"),
            str(root / "examples" / "cyanoesters.csv"),
        ],
        core_smiles_list=[("Azufre (S8)", "[S]")],
        threshold=0.0,
        ideal_rule="Lipinski",
    )
    assert len(gewald_all) > 0
    assert len(gewald_ideal) > 0
    assert (gewald_all["Classification"] == "Ideal").any()
    gewald_summary = gewald_all.attrs.get("run_summary", {})
    assert gewald_summary["evaluated"] == 54
    assert gewald_summary["ideal_unique"] == len(gewald_ideal)


def test_golden_biginelli_product_smiles(tmp_path):
    import mcrg_desktop as m

    if not _has_rdkit_and_pandas(m):
        return

    alde = _write_one_row_csv(tmp_path, "alde.csv", "O=Cc1ccccc1")
    keto = _write_one_row_csv(tmp_path, "keto.csv", "CC(=O)CC(=O)OC")

    df_all, df_ideal, _ = m.run_mcr(
        "Biginelli (3-CR)",
        [alde, keto],
        core_smiles_list=[("Urea", "[NH2]C(=O)[NH2]")],
        threshold=0.0,
        ideal_rule="Lipinski",
    )

    assert len(df_all) == 1
    assert len(df_ideal) == 1
    # Golden: canonical SMILES of first product (regression guard for SMARTS changes)
    assert df_all.iloc[0]["SMILES_Final"] == "COC(=O)C1=C(C)NC(=O)NC1c1ccccc1"
    assert "InChIKey" in df_all.columns


def test_golden_gbb_product_smiles(tmp_path):
    import mcrg_desktop as m

    if not _has_rdkit_and_pandas(m):
        return

    alde = _write_one_row_csv(tmp_path, "alde.csv", "O=Cc1ccccc1")
    iso = _write_one_row_csv(tmp_path, "iso.csv", "CC(C)(C)[N+]#[C-]")
    aminoazine = _write_one_row_csv(tmp_path, "aminoazine.csv", "Nc1ccccn1")

    df_all, df_ideal, _ = m.run_mcr(
        "GBB (3-CR)",
        [alde, iso, aminoazine],
        threshold=0.0,
        ideal_rule="Lipinski",
    )

    assert len(df_all) == 1
    assert len(df_ideal) == 1
    assert df_all.iloc[0]["Classification"] == "Ideal"
    assert df_all.iloc[0]["Review_Status"] == "Ideal"
    assert df_all.iloc[0]["SMILES_Final"] == "CC(C)(C)Nc1c(-c2ccccc2)nc2ccccn12"


def test_golden_gewald_malononitrile_variant(tmp_path):
    import mcrg_desktop as m

    if not _has_rdkit_and_pandas(m):
        return

    ketone = _write_one_row_csv(tmp_path, "ketone.csv", "CC(C)=O")
    nitrile = _write_one_row_csv(tmp_path, "malononitrile.csv", "N#CCC#N")

    df_all, df_ideal, _ = m.run_mcr(
        "Gewald (3-CR)",
        [ketone, nitrile],
        core_smiles_list=[("Azufre (S8)", "[S]")],
        threshold=0.0,
        ideal_rule="Lipinski",
    )

    assert len(df_all) == 1
    assert len(df_ideal) == 1
    assert df_all.iloc[0]["Classification"] == "Ideal"
    assert df_all.iloc[0]["SMILES_Final"] == "Cc1cc(C#N)c(N)s1"


def test_golden_mannich_no_product_reason(tmp_path):
    import mcrg_desktop as m

    if not _has_rdkit_and_pandas(m):
        return
    if "Mannich (3-CR)" not in m.MCR_CATALOGO:
        return

    alde = _write_one_row_csv(tmp_path, "alde.csv", "O=Cc1ccccc1")
    amine = _write_one_row_csv(tmp_path, "amine.csv", "CN")
    keto = _write_one_row_csv(tmp_path, "keto.csv", "CC(=O)CC(=O)OC")

    df_all, df_ideal, _ = m.run_mcr("Mannich (3-CR)", [alde, amine, keto], threshold=0.0, ideal_rule="Lipinski")
    assert len(df_all) == 1
    assert len(df_ideal) == 0
    assert df_all.iloc[0]["Classification"] == "Discarded"
    assert df_all.iloc[0]["Review_Status"] == "Error"
    assert df_all.iloc[0]["Failure_Reason"] == "No products generated by reaction SMARTS"


def test_golden_petasis_no_product_reason(tmp_path):
    import mcrg_desktop as m

    if not _has_rdkit_and_pandas(m):
        return
    if "Petasis (3-CR)" not in m.MCR_CATALOGO:
        return

    alde = _write_one_row_csv(tmp_path, "alde.csv", "O=Cc1ccccc1")
    amine = _write_one_row_csv(tmp_path, "amine.csv", "CN")
    bor = _write_one_row_csv(tmp_path, "bor.csv", "B(O)(O)C=C")

    df_all, df_ideal, _ = m.run_mcr("Petasis (3-CR)", [alde, amine, bor], threshold=0.0, ideal_rule="Lipinski")
    assert len(df_all) == 1
    assert len(df_ideal) == 0
    assert df_all.iloc[0]["Classification"] == "Discarded"
    assert df_all.iloc[0]["Failure_Reason"] == "No products generated by reaction SMARTS"
