def _has_rdkit_and_pandas(m):
    try:
        m._load_heavy()
        return bool(getattr(m, "_CHEM_READY", False)) and getattr(m, "pd", None) is not None
    except Exception:
        return False


def _write_one_row_csv(tmp_path, filename, smiles):
    p = tmp_path / filename
    p.write_text(f"NAME,SMILES\nX,{smiles}\n", encoding="utf-8")
    return str(p)


# Golden cases discovered/curated to be stable with the current RDKit+SMARTS model.
# Core reactions must produce sanitizable products from representative inputs.
CASES = {
    "Biginelli (3-CR)": {
        "component_smiles": ["O=Cc1ccccc1", "CC(=O)CC(=O)OC"],
        "core": ["Urea", "[NH2]C(=O)[NH2]"],
        "expect": {"type": "smiles", "value": "COC(=O)C1=C(C)NC(=O)NC1c1ccccc1"},
    },
    "GBB (3-CR)": {
        "component_smiles": ["O=Cc1ccccc1", "CC(C)(C)[N+]#[C-]", "Nc1ccccn1"],
        "core": None,
        "expect": {"type": "smiles", "value": "CC(C)(C)Nc1c(-c2ccccc2)nc2ccccn12"},
    },
    "Mannich (3-CR)": {
        "component_smiles": ["O=Cc1ccccc1", "CN", "CC(=O)C"],
        "core": None,
        "expect": {"type": "failure_reason", "value": "No products generated by reaction SMARTS"},
    },
    "Strecker (3-CR)": {
        "component_smiles": ["O=Cc1ccccc1", "CN"],
        "core": ["Cianuro (HCN/KCN)", "[C-]#[N]"],
        "expect": {"type": "failure_reason", "value": "No products generated by reaction SMARTS"},
    },
    "Petasis (3-CR)": {
        "component_smiles": ["O=Cc1ccccc1", "CN", "B(O)(O)c1ccccc1"],
        "core": None,
        "expect": {"type": "failure_reason", "value": "No products generated by reaction SMARTS"},
    },
    "Doebner (3-CR)": {
        "component_smiles": ["Nc1ccccc1", "O=Cc1ccccc1"],
        "core": ["Ácido pirúvico", "CC(=O)C(=O)O"],
        "expect": {"type": "failure_reason", "value": "Product sanitize failed"},
    },
    "Gewald (3-CR)": {
        "component_smiles": ["CC(=O)C", "CCOC(=O)CC#N"],
        "core": ["Azufre (S8)", "[S]"],
        "expect": {"type": "smiles", "value": "CCOC(=O)c1cc(C)sc1N"},
    },
    "Hantzsch (3-CR)": {
        "component_smiles": ["O=Cc1ccccc1", "CC(=O)CC(=O)OC", "CC(=O)CC(=O)OC"],
        "core": None,
        "expect": {"type": "failure_reason", "value": "No products generated by reaction SMARTS"},
    },
    "Asinger (4-CR)": {
        "component_smiles": ["ClCC(=O)C", "[NH3]", "CC=O"],
        "core": ["NaSH", "[S-]"],
        "expect": {"type": "smiles", "value": "CC1=NC(C)(O)[SH-]C1"},
    },
}


def test_golden_catalog_coverage(tmp_path):
    import mcrg_desktop as m

    if not _has_rdkit_and_pandas(m):
        return

    for mcr_key, info in m.MCR_CATALOGO.items():
        case = CASES.get(mcr_key)

        if case is None:
            # For reactions without a stable RDKit-parseable reactant setup in this version,
            # assert the engine returns an empty dataframe with a stable preview warning.
            files = []
            for i, _comp in enumerate(info["componentes"]):
                files.append(_write_one_row_csv(tmp_path, f"c{i}.csv", "NOT_A_SMILES"))
            df_all, df_ideal, preview = m.run_mcr(mcr_key, files, core_smiles_list=None, threshold=0.0, ideal_rule="Lipinski")
            assert len(df_all) == 0
            assert "empty or invalid" in preview
            continue

        files = []
        for i, smi in enumerate(case["component_smiles"]):
            files.append(_write_one_row_csv(tmp_path, f"{mcr_key}_{i}.csv", smi))
        core = case.get("core")
        core_list = [tuple(core)] if core else None

        df_all, df_ideal, preview = m.run_mcr(mcr_key, files, core_smiles_list=core_list, threshold=0.0, ideal_rule="Lipinski")
        assert len(df_all) == 1, f"{mcr_key} expected 1 row, got {len(df_all)}. preview={preview}"

        exp = case["expect"]
        if exp["type"] == "smiles":
            assert df_all.iloc[0]["SMILES_Final"] == exp["value"]
        elif exp["type"] == "failure_reason":
            assert df_all.iloc[0]["Failure_Reason"] == exp["value"]
        else:
            raise AssertionError(f"Unknown expect type for {mcr_key}: {exp['type']}")
