from __future__ import annotations

# NOTE:
# This module exists so non-desktop entrypoints (e.g. Streamlit/FastAPI)
# can reuse the reaction catalogue without importing the Tk desktop GUI.

MCR_CATALOGO = {
    "Biginelli (3-CR)": {
        "componentes": ["Aldehídos", "Beta-Cetoésteres"],
        "smarts": "[*:1][CH1:2]=[O:3].[NH2:4][C:5](=[O,S,N:6])[NH2:7].[*:8][C:9](=[O:10])[CH2:11][C:12](=[O:13])[O:14][*:15]>>[*:1][CH1:2]1[NH:7][C:5](=[O,S,N:6])[NH:4][C:9]([*:8])=[C:11]1[C:12](=[O:13])[O:14][*:15]",
        "opciones_centrales": {"Urea": "[NH2]C(=O)[NH2]", "Tiourea": "[NH2]C(=S)[NH2]", "Guanidina": "[NH2]C(=[NH])[NH2]"},
        "producto_ejemplo": "Cc1c(C(=O)OC)nc(C)nc1O",
        "doi": "10.3390/ph15081009",
        "info_es": "Síntesis de dihidropirimidinonas (DHPM). Catalizada por ácidos de Lewis o Brønsted.",
        "info_en": "Synthesis of Dihydropyrimidinones (DHPMs). Catalyzed by Lewis/Brønsted acids.",
    },
    "Passerini (3-CR)": {
        "componentes": ["Aldehídos/Cetonas", "Ácidos Carboxílicos", "Isocianuros"],
        "smarts": "[C:1]=[O:2].[O:3]=[C:4][OH:5].[C-:6]#[N+:7][C:8]>>[C:1]([O:5][C:4]=[O:3])([C:6](=[O:2])[NH:7][C:8])",
        "producto_ejemplo": "CC(=O)NC(c1ccccc1)C(=O)OC",
        "doi": "10.3762/bjoc.20.261",
        "info_es": "Formación de α-aciloxiamidas. Requiere condiciones suaves (sin catalizador).",
        "info_en": "Formation of α-acyloxyamides. Requires mild conditions (catalyst-free).",
    },
    "Mannich (3-CR)": {
        "componentes": ["Aldehídos", "Aminas Sec/Prim", "Carbonilos Enolizables"],
        "smarts": "[C:1]=[O:2].[N:3]([H]).[C:4](=[O:5])[CH1,CH2,CH3:6]>>[N:3][C:1][C:6][C:4](=[O:5])",
        "producto_ejemplo": "CC(=O)CC(=O)NCc1ccccc1",
        "doi": "10.3390/ph15081009",
        "info_es": "Reacción clásica para obtener β-aminocetonas (bases de Mannich).",
        "info_en": "Classic reaction for β-aminoketones (Mannich bases).",
    },
    "Strecker (3-CR)": {
        "componentes": ["Aldehídos/Cetonas", "Aminas"],
        "smarts": "[C:1]=[O:2].[N:3]([H]).[C-:4]#[N:5]>>[N:3][C:1][C:4]#[N:5]",
        "opciones_centrales": {"Cianuro (HCN/KCN)": "[C-]#[N]"},
        "producto_ejemplo": "CC(C#N)NCc1ccccc1",
        "doi": "10.3390/ph15081009",
        "info_es": "Síntesis de α-aminonitrilos, precursores directos de α-aminoácidos.",
        "info_en": "Synthesis of α-aminonitriles, direct precursors to α-amino acids.",
    },
    "Petasis (3-CR)": {
        "componentes": ["Aldehídos", "Aminas", "Ácidos Borónicos"],
        "smarts": "[C:1]=[O:2].[N:3]([H]).[B:4]([OH])([OH])[C:5]=[C:6]>>[N:3][C:1][C:5]=[C:6]",
        "producto_ejemplo": "C=CCNc1ccccc1",
        "doi": "10.3390/ph15081009",
        "info_es": "Aminación reductiva usando ácidos borónicos. Alta tolerancia funcional.",
        "info_en": "Reductive amination using boronic acids. High functional group tolerance.",
    },
    "Kabachnik-Fields (3-CR)": {
        "componentes": ["Aldehídos/Cetonas", "Aminas", "Fosfitos Dialquílicos"],
        "smarts": "[C:1]=[O:2].[N:3]([H]).[P:4](=[O:5])([O:6])([O:7])[H]>>[N:3][C:1][P:4](=[O:5])([O:6])([O:7])",
        "producto_ejemplo": "CCO[P@](=O)(OCC)NC(c1ccccc1)c2ccccc2",
        "doi": "10.3390/ph15081009",
        "info_es": "Síntesis de α-aminofosfonatos (análogos de aminoácidos con fósforo).",
        "info_en": "Synthesis of α-aminophosphonates (phosphorus-containing amino acid analogs).",
    },
    "GBB (3-CR)": {
        "componentes": ["Aldehídos", "Isocianuros", "2-Aminoazinas"],
        "smarts": "[C:1]=[O:2].[C-:3]#[N+:4][C:5].[n:6]1[c:7][c:8][c:9][c:10][c:11]1[NH2:12]>>[C:5][NH:4][c:3]2[n:6]3[c:7][c:8][c:9][c:10][c:11]3[n:12][c:1]2",
        "producto_ejemplo": "Cc1nc2ccccc2n1C(=O)c3ccccc3",
        "doi": "10.3390/ph15081009",
        "info_es": "Síntesis de imidazo[1,2-a]piridinas. Estructuras presentes en el fármaco Zolpidem.",
        "info_en": "Synthesis of imidazo[1,2-a]pyridines. Structures present in the drug Zolpidem.",
    },
    "Doebner (3-CR)": {
        "componentes": ["Anilinas", "Aldehídos"],
        "smarts": "[c:1]1[c:2][c:3][c:4][c:5][c:6]1[NH2:7].[C:8]=[O:9].[C:10](=[O:11])([C:12])[C:13](=[O:14])[OH:15]>>[c:1]1[c:2][c:3][c:4][c:5][c:6]21[N:7]=[C:8][C:12]=[C:10]2[C:13](=[O:14])[OH:15]",
        "opciones_centrales": {"Ácido pirúvico": "CC(=O)C(=O)O"},
        "producto_ejemplo": "CC(=O)c1c(C)c2ccccc2n1c3ccccc3",
        "doi": "10.3390/ph15081009",
        "info_es": "Modificación de la quinolina de Hantzsch. Produce ácidos cinconínicos.",
        "info_en": "Modification of the Hantzsch quinoline. Produces cinchoninic acids.",
    },
    "Gewald (3-CR)": {
        "componentes": ["Cetonas", "Alfa-Cianoésteres"],
        "smarts": "[CH2:1][C:2]=[O:3].[C:4](#N)[CH2:5][C:6](=[O:7])[O:8].[S:9]>>[c:1]1[c:2][s:9][c:4]([NH2])[c:5]1[C:6](=[O:7])[O:8]",
        "opciones_centrales": {"Azufre (S8)": "[S]"},
        "producto_ejemplo": "Cc1c(C#N)c(N)sc1C(=O)OC",
        "doi": "10.3390/ph15081009",
        "info_es": "Síntesis de 2-aminotiofenos trisustituidos. Núcleo heterocíclico clave.",
        "info_en": "Synthesis of trisubstituted 2-aminothiophenes. Key heterocyclic nucleus.",
    },
    "Hantzsch (3-CR)": {
        "componentes": ["Aldehídos", "Beta-Cetoéster (Equiv 1)", "Beta-Cetoéster (Equiv 2)"],
        "smarts": "[C:1]=[O:2].[C:3](=[O:4])[CH2:5][C:6](=[O:7])[O:8].[C:9](=[O:10])[CH:11]=[C:12]([NH2:13])[O:14]>>[C:1]1[C:5]([C:3]=[O:4])=[C:6]([O:8])[NH:13][C:12]([O:14])=[C:11]1[C:9]=[O:10]",
        "producto_ejemplo": "CC1=C(C(=O)OCC)NC(C)=C(C(=O)OC)C1c2ccccc2",
        "doi": "10.3390/ph15081009",
        "info_es": "Síntesis de 1,4-dihidropiridinas (1,4-DHP). Base estructural de los bloqueadores de canales de calcio.",
        "info_en": "Synthesis of 1,4-dihydropyridines (1,4-DHP). Structural basis for calcium channel blockers.",
    },
    "Ugi (4-CR)": {
        "componentes": ["Aldehídos/Cetonas", "Aminas Primarias", "Ácidos Carboxílicos", "Isocianuros"],
        "smarts": "[C:1]=[O:2].[N:3]([H])([H]).[O:4]=[C:5][OH:6].[C-:7]#[N+:8][C:9]>>[C:1]([N:3][C:5]=[O:4])([C:7](=[O:2])[NH:8][C:9])",
        "producto_ejemplo": "CC(=O)NC(c1ccccc1)C(=O)NCc2ccccc2",
        "doi": "10.3762/bjoc.20.261",
        "info_es": "La 'reacción maestra' de las MCR. Genera bis-amidas (peptoides) en un solo paso.",
        "info_en": "The 'master reaction' of MCRs. Generates bis-amides (peptoids) in one step.",
    },
    "Ugi-Smiles (4-CR)": {
        "componentes": ["Aldehídos", "Aminas Primarias", "Isocianuros", "Fenoles"],
        "smarts": "[C:1]=[O:2].[N:3]([H])([H]).[C-:4]#[N+:5][C:6].[c:7][OH:8]>>[C:1]([N:3][c:7])([C:4](=[O:2])[NH:5][C:6])",
        "producto_ejemplo": "CC(=O)NC(c1cc(O)ccc1)C(=O)NCc2ccccc2",
        "doi": "10.1016/B978-0-12-817467-8.00002-5",
        "info_es": "Variante del Ugi que involucra reordenamiento de Smiles.",
        "info_en": "Ugi variant involving Smiles rearrangement.",
    },
    "Asinger (4-CR)": {
        "componentes": ["Alfa-Halo Carbonilos", "Amoniaco/Aminas", "Carbonilos"],
        "smarts": "[Cl,Br,I:1][CH1,CH2:2][C:3]=[O:4].[NH3:5].[S:6].[C:7]=[O:8]>>[C:2]1[C:3]=[N:5][C:7]([*:8])[S:6]1",
        "opciones_centrales": {"NaSH": "[S-]"},
        "producto_ejemplo": "Cc1c(C=O)ncs1",
        "doi": "10.1016/B978-0-12-817467-8.00002-5",
        "info_es": "Síntesis de 3-tiazolinas y 3-tiazoles. Precursores de penicilinas.",
        "info_en": "Synthesis of 3-thiazolines and 3-thiazoles. Precursors to penicillins.",
    },
    "Bucherer-Bergs (4-CR)": {
        "componentes": ["Cetonas"],
        "smarts": "[C:1](=[O:2])([C:3])([C:4]).[C-:5]#[N:6].[NH3:7].[C:8](=[O:9])=[O:10]>>[C:1]1([C:3])([C:4])[NH:6][C:8](=[O:9])[NH:7][C:5]1=[O:2]",
        "opciones_centrales": {"Cianuro (KCN)": "[C-]#[N]", "Carbonato de Amonio": "NC(=O)N", "CO2": "O=C=O"},
        "producto_ejemplo": "CC1(C)NC(=O)NC1=O",
        "doi": "10.1016/B978-0-12-817467-8.00002-5",
        "info_es": "Síntesis de hidantoínas (imidazolidina-2,4-diona).",
        "info_en": "Synthesis of hydantoins (imidazolidine-2,4-dione).",
    },
}

