import itertools
import json
import pathlib
import tempfile
import traceback

import sys

# Ensure repo root (containing mcrg_desktop.py) is importable even when launched via conda run.
REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

import mcrg_desktop as m


def main():
    m._load_heavy()

    cand = {
        "Aldehídos": ["O=Cc1ccccc1", "CC=O"],
        "Aldehídos/Cetonas": ["O=Cc1ccccc1", "CC=O", "CC(=O)C"],
        "Cetonas": ["CC(=O)C", "CCC(=O)C"],
        "Carbonilos": ["CC=O", "CC(=O)C"],
        "Carbonilos Enolizables": ["CC(=O)C", "CC(=O)CC(=O)OC"],
        "Beta-Cetoésteres": ["CC(=O)CC(=O)OC"],
        "Beta-Cetoéster (Equiv 1)": ["CC(=O)CC(=O)OC"],
        "Beta-Cetoéster (Equiv 2)": ["CC(=O)CC(=O)OC"],
        "Ácidos Carboxílicos": ["CC(=O)O", "O=C(O)c1ccccc1"],
        "Ácidos Borónicos": ["B(O)(O)c1ccccc1", "B(O)(O)C=C"],
        # RDKit-friendly isocyanides (R–N#C)
        "Isocianuros": ["CN#C", "CCN#C", "c1ccccc1N#C"],
        "Aminas": ["CN", "CCN"],
        "Aminas Primarias": ["CN", "CCN"],
        "Aminas Sec/Prim": ["CN", "CCN"],
        "Fenoles": ["c1ccc(cc1)O", "Oc1ccccc1C"],
        # Dialkyl phosphite / phosphonate-like P(=O)(OR)(OR)H
        "Fosfitos Dialquílicos": ["COP(=O)(OC)H", "CCOP(=O)(OCC)H"],
        "2-Aminoazinas": ["Nc1ncccc1"],
        "Anilinas": ["Nc1ccccc1"],
        "Alfa-Cianoésteres": ["N#CC(C(=O)OC)C"],
        "Alfa-Halo Carbonilos": ["ClCC(=O)C"],
        "Amoniaco/Aminas": ["[NH3]", "CN"],
    }
    default = ["CC=O"]

    def try_reaction(mcr_key: str):
        info = m.MCR_CATALOGO[mcr_key]
        comps = info["componentes"]
        opts = info.get("opciones_centrales") or {}
        core = None
        core_name = None
        if opts:
            core_name = next(iter(opts.keys()))
            core = opts[core_name]

        lists = [cand.get(c, default) for c in comps]
        max_trials = 600
        trials = 0

        with tempfile.TemporaryDirectory() as td:
            td = pathlib.Path(td)
            for combo in itertools.product(*lists):
                trials += 1
                if trials > max_trials:
                    break
                files = []
                for i, smi in enumerate(combo):
                    p = td / f"c{i}.csv"
                    p.write_text(f"NAME,SMILES\nX,{smi}\n", encoding="utf-8")
                    files.append(str(p))
                core_list = [(core_name, core)] if core else None
                df_all, _df_ideal, _prev = m.run_mcr(
                    mcr_key, files, core_smiles_list=core_list, threshold=0.0
                )
                if len(df_all) != 1:
                    continue
                row = df_all.iloc[0]
                smi_final = str(row.get("SMILES_Final", "") or "")
                fr = str(row.get("Failure_Reason", "") or "")
                cls = str(row.get("Classification", "") or "")

                if smi_final:
                    return {
                        "component_smiles": list(combo),
                        "core": [core_name, core] if core else None,
                        "expect": {
                            "type": "smiles",
                            "value": smi_final,
                            "classification": cls,
                        },
                    }
                if fr in (
                    "No products generated by reaction SMARTS",
                    "Product sanitize failed",
                ):
                    return {
                        "component_smiles": list(combo),
                        "core": [core_name, core] if core else None,
                        "expect": {
                            "type": "failure_reason",
                            "value": fr,
                            "classification": cls,
                        },
                    }
        return None

    out = {"cases": {}, "failed": [], "errors": {}}
    for k in m.MCR_CATALOGO.keys():
        try:
            res = try_reaction(k)
            if res is None:
                out["failed"].append(k)
            else:
                out["cases"][k] = res
        except Exception:
            out["errors"][k] = traceback.format_exc(limit=3)

    pathlib.Path("golden_cases.json").write_text(
        json.dumps(out, indent=2, ensure_ascii=False), encoding="utf-8"
    )


if __name__ == "__main__":
    main()

